name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '$HOME/Qt'

    - name: Verify Qt installation
      run: |
        echo "Verifying Qt directory structure"
        ls -R $HOME/Qt || { echo "Qt installation failed"; exit 1; }

    - name: Set up Qt environment
      run: |
        if [ -f "$HOME/Qt/5.15.2/gcc_64/bin/qt-env.sh" ]; then
          source $HOME/Qt/5.15.2/gcc_64/bin/qt-env.sh
        else
          echo "qt-env.sh not found"
          exit 1
        fi

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qt5-qmake g++

    - name: Build the project
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./test/TestExecutable

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '$HOME/Qt'
    
    - name: Verify Qt installation
      run: |
        echo "Verifying Qt directory structure"
        ls -R $HOME/Qt || { echo "Qt installation failed"; exit 1; }

    - name: Set up Qt environment
      run: |
        if [ -f "$HOME/Qt/5.15.2/gcc_64/bin/qt-env.sh" ]; then
          source $HOME/Qt/5.15.2/gcc_64/bin/qt-env.sh
        else
          echo "qt-env.sh not found"
          exit 1
        fi

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qt5-qmake g++

    - name: Build the project
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Deploy artifact
      run: echo "Deploy step here"  # Replace with actual deployment commands
